INSERT INTO common.currency_type_mw (currency_type, currency_type_name, currency_type_desc, wikidata_id) VALUES
    ('F', 'Fiat Currency', 'Government issued currency which is not backed by a precious metals, nor commodities nor any other tangible assets.', 'Q240532'),
    ('C', 'Commodity Money', 'A money whosh value is derived from a commodity, and has an intrinsic value.', 'Q1470163'),
    ('R', 'Representative Money', 'A medium of exchange which has very little or no intrinsic value of its own.', 'Q7314254'),
    ('D', 'Digital Currency', 'A type of money that is stored or exchanged on digital computers over the internet.', 'Q10836209');


INSERT INTO common.currency_subtype_mw (currency_subtype, currency_subtype_name, currency_type, currency_subtype_desc, wikidata_id) VALUES
    ('C', 'Cryptocurrency', 'D', 'A digital currency that is designed to work over the network.', 'Q13479982'),
    ('F', 'Central Bank Digital Currency (CBDC)', 'D', 'A digital fiat currency which is issued by a central bank.', 'Q39086217'),
    ('S', 'Stablecoins', 'D', 'A type of cryptocurrency where the value is pegged to a referencing asset.', 'Q55582088'),
    ('V', 'Virtual Currency', 'D', 'Digital currency which are unregulated and typically controlled by its developers.', 'Q4112083');


INSERT INTO common.currency_mw (currency_code, currency_name, currency_type) VALUES
    ('AED', 'United Arab Emirates Dirham', 'F'),
    ('AFN', 'Afghan Afghani', 'F'),
    ('ALL', 'Albanian Lek', 'F'),
    ('AMD', 'Armenian Dram', 'F'),
    ('ANG', 'Netherlands Antillean Guilder', 'F'),
    ('AOA', 'Angolan Kwanza', 'F'),
    ('ARS', 'Argentine Peso', 'F'),
    ('AUD', 'Australian Dollar', 'F'),
    ('AWG', 'Aruban Florin', 'F'),
    ('AZN', 'Azerbaijani Manat', 'F'),
    ('BAM', 'Bosnia And Herzegovina Convertible Mark', 'F'),
    ('BBD', 'Barbados Dollar', 'F'),
    ('BDT', 'Bangladeshi Taka', 'F'),
    ('BGN', 'Bulgarian Lev', 'F'),
    ('BHD', 'Bahraini Dinar', 'F'),
    ('BMD', 'Bermudian Dollar', 'F'),
    ('BND', 'Brunei Dollar', 'F'),
    ('BOB', 'Boliviano', 'F'),
    ('BOV', 'Bolivian Mvdol (Funds Code)', 'F'),
    ('BRL', 'Brazilian Real', 'F'),
    ('BSD', 'Bahamian Dollar', 'F'),
    ('BTN', 'Bhutanese Ngultrum', 'F'),
    ('BWP', 'Botswana Pula', 'F'),
    ('BYR', 'Belarusian Ruble', 'F'),
    ('BZD', 'Belize Dollar', 'F'),
    ('CAD', 'Canadian Dollar', 'F'),
    ('CDF', 'Congolese Franc', 'F'),
    ('CHE', 'Wir Euro (Complementary Currency)', 'F'),
    ('CHF', 'Swiss Franc', 'F'),
    ('CHW', 'Wir Franc (Complementary Currency)', 'F'),
    ('CLF', 'Unidad De Fomento (Funds Code)', 'F'),
    ('CNY', 'Renminbi[6]', 'F'),
    ('COP', 'Colombian Peso', 'F'),
    ('COU', 'Unidad De Valor Real (Uvr) (Funds Code)[7]', 'F'),
    ('CRC', 'Costa Rican Colon', 'F'),
    ('CUP', 'Cuban Peso', 'F'),
    ('CVE', 'Cape Verdean Escudo', 'F'),
    ('CZK', 'Czech Koruna', 'F'),
    ('DKK', 'Danish Krone', 'F'),
    ('DOP', 'Dominican Peso', 'F'),
    ('DZD', 'Algerian Dinar', 'F'),
    ('EGP', 'Egyptian Pound', 'F'),
    ('ERN', 'Eritrean Nakfa', 'F'),
    ('ETB', 'Ethiopian Birr', 'F'),
    ('EUR', 'Euro', 'F'),
    ('FJD', 'Fiji Dollar', 'F'),
    ('FKP', 'Falkland Islands Pound', 'F'),
    ('GBP', 'Pound Sterling', 'F'),
    ('GEL', 'Georgian Lari', 'F'),
    ('GHS', 'Ghanaian Cedi', 'F'),
    ('GIP', 'Gibraltar Pound', 'F'),
    ('GMD', 'Gambian Dalasi', 'F'),
    ('GTQ', 'Guatemalan Quetzal', 'F'),
    ('GYD', 'Guyanese Dollar', 'F'),
    ('HKD', 'Hong Kong Dollar', 'F'),
    ('HNL', 'Honduran Lempira', 'F'),
    ('HTG', 'Haitian Gourde', 'F'),
    ('HUF', 'Hungarian Forint', 'F'),
    ('IDR', 'Indonesian Rupiah', 'F'),
    ('ILS', 'Israeli New Shekel', 'F'),
    ('INR', 'Indian Rupee', 'F'),
    ('IQD', 'Iraqi Dinar', 'F'),
    ('IRR', 'Iranian Rial', 'F'),
    ('JMD', 'Jamaican Dollar', 'F'),
    ('JPY', 'Japanese Yen', 'F'),
    ('JOD', 'Jordanian Dinar', 'F'),
    ('KES', 'Kenyan Shilling', 'F'),
    ('KGS', 'Kyrgyzstani Som', 'F'),
    ('KHR', 'Cambodian Riel', 'F'),
    ('KPW', 'North Korean Won', 'F'),
    ('KRW', 'South Korean Won', 'F'),
    ('KWD', 'Kuwaiti Dinar', 'F'),
    ('KYD', 'Cayman Islands Dollar', 'F'),
    ('KZT', 'Kazakhstani Tenge', 'F'),
    ('LAK', 'Lao Kip', 'F'),
    ('LBP', 'Lebanese Pound', 'F'),
    ('LKR', 'Sri Lankan Rupee', 'F'),
    ('LRD', 'Liberian Dollar', 'F'),
    ('LSL', 'Lesotho Loti', 'F'),
    ('LYD', 'Libyan Dinar', 'F'),
    ('MAD', 'Moroccan Dirham', 'F'),
    ('MDL', 'Moldovan Leu', 'F'),
    ('MGA', 'Malagasy Ariary', 'F'),
    ('MKD', 'Macedonian Denar', 'F'),
    ('MMK', 'Myanmar Kyat', 'F'),
    ('MNT', 'Mongolian Tã¶Grã¶G', 'F'),
    ('MOP', 'Macanese Pataca', 'F'),
    ('MRU', 'Mauritanian Ouguiya', 'F'),
    ('MUR', 'Mauritian Rupee', 'F'),
    ('MVR', 'Maldivian Rufiyaa', 'F'),
    ('MWK', 'Malawian Kwacha', 'F'),
    ('MXN', 'Mexican Peso', 'F'),
    ('MXV', 'Mexican Unidad De Inversion (Udi) (Funds Code)', 'F'),
    ('MYR', 'Malaysian Ringgit', 'F'),
    ('MZN', 'Mozambican Metical', 'F'),
    ('NAD', 'Namibian Dollar', 'F'),
    ('NGN', 'Nigerian Naira', 'F'),
    ('NIO', 'Nicaraguan Cã³rdoba', 'F'),
    ('NOK', 'Norwegian Krone', 'F'),
    ('NPR', 'Nepalese Rupee', 'F'),
    ('NZD', 'New Zealand Dollar', 'F'),
    ('OMR', 'Omani Rial', 'F'),
    ('PAB', 'Panamanian Balboa', 'F'),
    ('PEN', 'Peruvian Sol', 'F'),
    ('PGK', 'Papua New Guinean Kina', 'F'),
    ('PHP', 'Philippine Peso[11]', 'F'),
    ('PKR', 'Pakistani Rupee', 'F'),
    ('PLN', 'Polish Zloty', 'F'),
    ('QAR', 'Qatari Riyal', 'F'),
    ('RON', 'Romanian Leu', 'F'),
    ('RSD', 'Serbian Dinar', 'F'),
    ('RUB', 'Russian Ruble', 'F'),
    ('SAR', 'Saudi Riyal', 'F'),
    ('SBD', 'Solomon Islands Dollar', 'F'),
    ('SCR', 'Seychelles Rupee', 'F'),
    ('SDG', 'Sudanese Pound', 'F'),
    ('SEK', 'Swedish Krona (Plural: Kronor)', 'F'),
    ('SGD', 'Singapore Dollar', 'F'),
    ('SHP', 'Saint Helena Pound', 'F'),
    ('SLE', 'Sierra Leonean Leone (New Leone)[12][13][14]', 'F'),
    ('SOS', 'Somalian Shilling', 'F'),
    ('SRD', 'Surinamese Dollar', 'F'),
    ('SSP', 'South Sudanese Pound', 'F'),
    ('STD', 'Sã£O Tomã© And Prã­Ncipe Dobra', 'F'),
    ('STN', 'Sao Tomean Dobra', 'F'),
    ('SVC', 'Salvadoran Colã³n', 'F'),
    ('SYP', 'Syrian Pound', 'F'),
    ('SZL', 'Swazi Lilangeni', 'F'),
    ('THB', 'Thai Baht', 'F'),
    ('TJS', 'Tajikistani Somoni', 'F'),
    ('TMT', 'Turkmenistan Manat', 'F'),
    ('TND', 'Tunisian Dinar', 'F'),
    ('TOP', 'Tongan Paanga', 'F'),
    ('TRY', 'Turkish Lira', 'F'),
    ('TTD', 'Trinidad And Tobago Dollar', 'F'),
    ('TWD', 'New Taiwan Dollar', 'F'),
    ('TZS', 'Tanzanian Shilling', 'F'),
    ('UAH', 'Ukrainian Hryvnia', 'F'),
    ('USD', 'United States Dollar', 'F'),
    ('USN', 'United States Dollar (Next Day) (Funds Code)', 'F'),
    ('UYU', 'Uruguayan Peso', 'F'),
    ('UYW', 'Unidad Previsional[16]', 'F'),
    ('UZS', 'Uzbekistani Sum', 'F'),
    ('VED', 'Venezuelan Digital Bolã­Var[17]', 'F'),
    ('VES', 'Venezuelan Sovereign Bolã­Var[11]', 'F'),
    ('WST', 'Samoan Tala', 'F'),
    ('XCD', 'East Caribbean Dollar', 'F'),
    ('YER', 'Yemeni Rial', 'F'),
    ('ZAR', 'South African Rand', 'F'),
    ('ZMW', 'Zambian Kwacha', 'F'),
    ('ZWG', 'Zimbabwe Gold', 'F'),
    ('BIF', 'Burundian Franc', 'F'),
    ('BTC', 'Bitcoin', 'F'),
    ('BYN', 'New Belarusian Ruble', 'F'),
    ('CLP', 'Chilean Peso', 'F'),
    ('CNH', 'Chinese Yuan Offshore', 'F'),
    ('CUC', 'Cuban Convertible Peso', 'F'),
    ('DJF', 'Djiboutian Franc', 'F'),
    ('GGP', 'Guernsey Pound', 'F'),
    ('GNF', 'Guinean Franc', 'F'),
    ('HRK', 'Croatian Kuna', 'F'),
    ('IMP', 'Manx Pound', 'F'),
    ('ISK', 'Icelandic Krã³na', 'F'),
    ('JEP', 'Jersey Pound', 'F'),
    ('KMF', 'Comorian Franc', 'F'),
    ('LTL', 'Lithuanian Litas', 'F'),
    ('LVL', 'Latvian Lats', 'F'),
    ('PYG', 'Paraguayan Guarani', 'F'),
    ('RWF', 'Rwandan Franc', 'F'),
    ('SLL', 'Sierra Leonean Leone', 'F'),
    ('UGX', 'Ugandan Shilling', 'F'),
    ('VEF', 'Venezuelan Bolã­Var Fuerte', 'F'),
    ('VND', 'Vietnamese Dong', 'F'),
    ('VUV', 'Vanuatu Vatu', 'F'),
    ('XAF', 'Cfa Franc Beac', 'F'),
    ('XAG', 'Silver (Troy Ounce)', 'F'),
    ('XAU', 'Gold (Troy Ounce)', 'F'),
    ('XCG', 'Caribbean Guilder	', 'F'),
    ('XDR', 'Special Drawing Rights', 'F'),
    ('XOF', 'Cfa Franc Bceao', 'F'),
    ('XPF', 'Cfp Franc', 'F'),
    ('ZMK', 'Zambian Kwacha (Pre-2013)', 'F'),
    ('ZWL', 'Zimbabwean Dollar', 'F'),
    ('BYD', 'Belarusian Ruble (Alternate)', 'F');
